project_id = "fgeyphtaehvbitwcnvoa"

[functions.create-staff]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.delete-staff]
enabled = true
verify_jwt = true
import_map = "./functions/delete-staff/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-staff/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-staff/*.html" ]

[functions.generate-daily-deliveries]
enabled = true
verify_jwt = true
import_map = "./functions/generate-daily-deliveries/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-daily-deliveries/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-daily-deliveries/*.html" ]
